export const SET_LAST_VISITED_TIMETABLE = 'SET_LAST_VISITED_TIMETABLE';
export const SET_LOADING = 'SET_LOADING';
export const TOGGLE_ACCENTED_BORDERS = 'TOGGLE_ACCENTED_BORDERS';
export const TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME';
