export const SET_LAST_VISITED_TIMETABLE = 'SET_LAST_VISITED_TIMETABLE';
export const SET_FETCHING = 'SET_FETCHING';
export const TOGGLE_ACCENTED_BORDERS = 'TOGGLE_ACCENTED_BORDERS';
export const TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME';
